name: Update README Stats

on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create stats directory
        run: mkdir -p profile

      - name: Generate GitHub Stats Card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=arulpanditaa&show_icons=true&theme=tokyonight&hide_border=true
          path: profile/github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true

      - name: Generate Top Languages Card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=arulpanditaa&layout=compact&langs_count=8&theme=tokyonight&hide_border=true
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true

      - name: Commit updated cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git diff --staged --quiet || git commit -m "Update GitHub profile stats"
          git push
